import type {
  Category,
  DashboardMetric,
  DemoUser,
  FarmerProfile,
  MandiRate,
  Order,
  Product,
  Review,
  WeatherInsight,
} from "@/lib/types";
import { slugify } from "@/utils/format";

const imageLibrary = {
  heroHarvest: "/images/photos/farm-landscape.jpg",
  heroGreenhouse: "/images/photos/seedlings.jpg",
  heroMarketplace: "/images/photos/vegetable-market.jpg",
  mango: "/images/photos/mangoes.jpg",
  leafy: "/images/products/palak.webp",
  dairy: "/images/photos/dairy-milk.jpg",
  grains: "/images/photos/rice-grains.jpg",
  seeds: "/images/photos/seedlings.jpg",
  onions: "/images/photos/onions.jpg",
  spices: "/images/photos/spices.jpg",
  paneer: "/images/photos/dairy-milk.jpg",
  rice: "/images/photos/rice-grains.jpg",
  banana: "/images/photos/bananas.jpg",
  tomato: "/images/photos/tomatoes.jpg",
  chillies: "/images/photos/spices.jpg",
  oil: "/images/photos/cooking-oil.jpg",
  fertilizer: "/images/photos/farm-landscape.jpg",
  pesticide: "/images/photos/farm-landscape.jpg",
  compost: "/images/photos/farm-landscape.jpg",
  nursery: "/images/photos/seedlings.jpg",
};

export const categories: Category[] = [
  {
    id: "fruits",
    name: "Fruits",
    slug: "fruits",
    description: "Aam, banana, orange, papaya and other seasonal fruits.",
    accent: "from-orange-100 to-amber-50",
  },
  {
    id: "vegetables",
    name: "Vegetables",
    slug: "vegetables",
    description: "Daily-use sabzi like pyaz, palak, tamatar, bhindi and hari mirch.",
    accent: "from-emerald-100 to-lime-50",
  },
  {
    id: "grains",
    name: "Grains & Pantry",
    slug: "grains",
    description: "Atta, chawal, dal, masalas and pantry staples from local growers.",
    accent: "from-yellow-100 to-stone-50",
  },
  {
    id: "dairy",
    name: "Dairy",
    slug: "dairy",
    description: "Fresh paneer, ghee and village dairy products.",
    accent: "from-sky-100 to-cyan-50",
  },
  {
    id: "seeds",
    name: "Seeds",
    slug: "seeds",
    description: "Beej packs for farm sowing and kitchen garden use.",
    accent: "from-rose-100 to-orange-50",
  },
  {
    id: "fertilisers",
    name: "Fertilisers",
    slug: "fertilisers",
    description: "NPK, bio potash, vermicompost and growth boosters for stronger crops.",
    accent: "from-lime-100 to-green-50",
  },
  {
    id: "crop-care",
    name: "Crop Care",
    slug: "crop-care",
    description: "Pesticides, neem-based protection and nursery care inputs.",
    accent: "from-emerald-100 to-white",
  },
];

export const farmers: FarmerProfile[] = [
  {
    id: "farmer-1",
    userId: "user-2",
    name: "Rakesh Kumar",
    farmName: "Khet Se Ghar Farm",
    shopName: "Khet Se Ghar Farm",
    shopLocation: "Ludhiana Punjab",
    phone: "9988776655",
    state: "Punjab",
    district: "Ludhiana",
    rating: 4.8,
    verified: true,
    yearsActive: 11,
    speciality: ["Palak, tamatar and hari sabzi", "Daily mandi supply"],
    responseTime: "within 15 mins",
  },
  {
    id: "farmer-2",
    userId: "user-4",
    name: "Anita Patil",
    farmName: "Sahyadri Shetkari Farm",
    shopName: "Sahyadri Shetkari Farm",
    shopLocation: "Nashik Maharashtra",
    phone: "9898989898",
    state: "Maharashtra",
    district: "Nashik",
    rating: 4.7,
    verified: true,
    yearsActive: 8,
    speciality: ["Nashik pyaz", "Seasonal fruits", "Bhindi"],
    responseTime: "within 25 mins",
  },
  {
    id: "farmer-3",
    userId: "user-5",
    name: "Mahesh Gowda",
    farmName: "Namma Ooru Organics",
    shopName: "Namma Ooru Organics",
    shopLocation: "Mysuru Karnataka",
    phone: "9797979797",
    state: "Karnataka",
    district: "Mysuru",
    rating: 4.9,
    verified: true,
    yearsActive: 13,
    speciality: ["Atta and rice", "Ghee, paneer and haldi"],
    responseTime: "within 30 mins",
  },
];

function buildProduct(
  data: Omit<Product, "slug">,
): Product {
  return {
    ...data,
    slug: slugify(`${data.name}-${data.farmerName}`),
  };
}

function gallery(...images: string[]) {
  return images;
}

export const products: Product[] = [
  buildProduct({
    id: "prod-1",
    name: "Hapus Aam Peti",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "fruits",
    state: "Maharashtra",
    description:
      "Sweet mangoes packed in a simple peti for family orders, gifting, and weekend fruit buyers.",
    tags: ["Seasonal", "Family pack", "Best seller"],
    unit: "3 kg peti",
    stock: 96,
    organic: true,
    price: 899,
    originalPrice: 1099,
    deliveryTime: "1-2 days",
    rating: 4.8,
    reviewCount: 138,
    images: gallery(
      imageLibrary.mango,
      imageLibrary.heroHarvest,
      imageLibrary.heroMarketplace,
    ),
    color: "from-amber-100 to-orange-50",
    harvestDate: "2026-04-20",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-2",
    name: "Fresh Palak Bunch",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "vegetables",
    state: "Punjab",
    description:
      "Fresh green palak tied in bunches and sent quickly for home cooking, dal, paratha and juice use.",
    tags: ["Leafy", "Fast moving", "Fresh cut"],
    unit: "500 g",
    stock: 150,
    organic: true,
    price: 85,
    originalPrice: 110,
    deliveryTime: "Same day",
    rating: 4.6,
    reviewCount: 71,
    images: gallery(
      imageLibrary.leafy,
      imageLibrary.heroHarvest,
      imageLibrary.nursery,
    ),
    color: "from-green-100 to-lime-50",
    harvestDate: "2026-04-27",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-3",
    name: "A2 Desi Ghee",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "dairy",
    state: "Karnataka",
    description:
      "Bilona style ghee made in small batches and packed for homes, sweet shops and repeat dairy buyers.",
    tags: ["Dairy", "Premium", "Village made"],
    unit: "1 litre",
    stock: 46,
    organic: false,
    price: 1199,
    originalPrice: 1390,
    deliveryTime: "2-4 days",
    rating: 4.9,
    reviewCount: 94,
    images: gallery(
      imageLibrary.dairy,
      imageLibrary.heroGreenhouse,
      imageLibrary.heroMarketplace,
    ),
    color: "from-yellow-100 to-orange-50",
    harvestDate: "2026-04-15",
    featured: true,
    trending: false,
  }),
  buildProduct({
    id: "prod-4",
    name: "Chakki Fresh Atta",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "Freshly milled atta for chapati and paratha use, with a simple everyday household pack size.",
    tags: ["Atta", "Daily use", "Household"],
    unit: "5 kg",
    stock: 72,
    organic: false,
    price: 399,
    originalPrice: 470,
    deliveryTime: "2-3 days",
    rating: 4.5,
    reviewCount: 49,
    images: gallery(
      imageLibrary.grains,
      imageLibrary.heroHarvest,
      imageLibrary.heroGreenhouse,
    ),
    color: "from-yellow-100 to-stone-50",
    harvestDate: "2026-04-18",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-5",
    name: "Hybrid Tamatar Beej Pack",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "seeds",
    state: "Punjab",
    description:
      "High-germination tamatar seeds useful for nursery work, kitchen gardens and small farm sowing.",
    tags: ["Beej", "Nursery", "Kitchen garden"],
    unit: "250 g",
    stock: 120,
    organic: false,
    price: 260,
    originalPrice: 325,
    deliveryTime: "2-5 days",
    rating: 4.3,
    reviewCount: 35,
    images: gallery(
      imageLibrary.seeds,
      imageLibrary.nursery,
      imageLibrary.tomato,
    ),
    color: "from-rose-100 to-orange-50",
    harvestDate: "2026-04-12",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-6",
    name: "Nashik Pyaz",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "vegetables",
    state: "Maharashtra",
    description:
      "Clean and sorted onions from Nashik, useful for homes, kirana stores, caterers and bulk kitchen use.",
    tags: ["Popular", "Bulk pack", "Kirana"],
    unit: "5 kg",
    stock: 190,
    organic: false,
    price: 220,
    originalPrice: 280,
    deliveryTime: "1-3 days",
    rating: 4.4,
    reviewCount: 82,
    images: gallery(
      imageLibrary.onions,
      imageLibrary.heroMarketplace,
      imageLibrary.heroHarvest,
    ),
    color: "from-rose-100 to-pink-50",
    harvestDate: "2026-04-26",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-7",
    name: "Organic Haldi Fingers",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "Sun-dried haldi fingers with strong color and aroma for home grinding and spice use.",
    tags: ["Haldi", "Masala", "Pantry"],
    unit: "2 kg",
    stock: 76,
    organic: true,
    price: 540,
    originalPrice: 620,
    deliveryTime: "2-4 days",
    rating: 4.8,
    reviewCount: 51,
    images: gallery(
      imageLibrary.spices,
      imageLibrary.heroHarvest,
      imageLibrary.heroGreenhouse,
    ),
    color: "from-yellow-100 to-lime-50",
    harvestDate: "2026-04-17",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-8",
    name: "Fresh Paneer Block",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "dairy",
    state: "Karnataka",
    description:
      "Soft paneer prepared daily and packed for homes, tiffin services, cafes and small food businesses.",
    tags: ["Dairy", "Fresh", "Daily use"],
    unit: "1 kg",
    stock: 33,
    organic: false,
    price: 360,
    originalPrice: 425,
    deliveryTime: "Same day",
    rating: 4.7,
    reviewCount: 64,
    images: gallery(
      imageLibrary.paneer,
      imageLibrary.dairy,
      imageLibrary.heroGreenhouse,
    ),
    color: "from-slate-100 to-cyan-50",
    harvestDate: "2026-04-28",
    featured: true,
    trending: false,
  }),
  buildProduct({
    id: "prod-9",
    name: "Sona Masoori Rice",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "Light everyday rice cleaned and packed for regular family meals and mess kitchens.",
    tags: ["Rice", "Daily use", "Value pack"],
    unit: "10 kg",
    stock: 54,
    organic: false,
    price: 699,
    originalPrice: 780,
    deliveryTime: "2-4 days",
    rating: 4.6,
    reviewCount: 43,
    images: gallery(
      imageLibrary.rice,
      imageLibrary.grains,
      imageLibrary.heroMarketplace,
    ),
    color: "from-yellow-100 to-stone-50",
    harvestDate: "2026-04-14",
    featured: true,
    trending: false,
  }),
  buildProduct({
    id: "prod-10",
    name: "Toor Dal Clean Pack",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "Clean toor dal with simple household packing for daily dal, sambar and khichdi cooking.",
    tags: ["Dal", "Kitchen staple", "Family pack"],
    unit: "5 kg",
    stock: 68,
    organic: false,
    price: 620,
    originalPrice: 710,
    deliveryTime: "2-4 days",
    rating: 4.5,
    reviewCount: 39,
    images: gallery(
      imageLibrary.grains,
      imageLibrary.spices,
      imageLibrary.heroGreenhouse,
    ),
    color: "from-yellow-100 to-orange-50",
    harvestDate: "2026-04-10",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-11",
    name: "Bhindi Fresh",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "vegetables",
    state: "Maharashtra",
    description:
      "Tender bhindi sorted for easy home cooking and direct supply to local vegetable counters.",
    tags: ["Sabzi", "Fresh", "Fast moving"],
    unit: "1 kg",
    stock: 84,
    organic: false,
    price: 95,
    originalPrice: 120,
    deliveryTime: "Same day",
    rating: 4.4,
    reviewCount: 28,
    images: gallery(
      imageLibrary.leafy,
      imageLibrary.heroHarvest,
      imageLibrary.heroMarketplace,
    ),
    color: "from-lime-100 to-green-50",
    harvestDate: "2026-04-29",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-12",
    name: "Elaichi Banana",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "fruits",
    state: "Karnataka",
    description:
      "Sweet bananas packed for fruit bowls, breakfast, tiffin and school snack use.",
    tags: ["Fruit", "Kids favorite", "Daily use"],
    unit: "1 dozen",
    stock: 102,
    organic: false,
    price: 78,
    originalPrice: 95,
    deliveryTime: "1-2 days",
    rating: 4.6,
    reviewCount: 57,
    images: gallery(
      imageLibrary.banana,
      imageLibrary.heroHarvest,
      imageLibrary.heroMarketplace,
    ),
    color: "from-yellow-100 to-lime-50",
    harvestDate: "2026-04-25",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-13",
    name: "Desi Tamatar",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "vegetables",
    state: "Punjab",
    description:
      "Bright red tamatar for daily tadka, curry, salad and small retail counter supply.",
    tags: ["Sabzi", "Kitchen staple", "Fresh harvest"],
    unit: "1 kg",
    stock: 118,
    organic: false,
    price: 52,
    originalPrice: 68,
    deliveryTime: "Same day",
    rating: 4.5,
    reviewCount: 73,
    images: gallery(
      imageLibrary.tomato,
      imageLibrary.heroMarketplace,
      imageLibrary.heroHarvest,
    ),
    color: "from-red-100 to-orange-50",
    harvestDate: "2026-04-29",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-14",
    name: "Hari Mirch",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "vegetables",
    state: "Punjab",
    description:
      "Sharp green chillies for regular kitchen use, chutney, pickle and local stall supply.",
    tags: ["Spicy", "Kitchen add-on", "Fresh"],
    unit: "250 g",
    stock: 140,
    organic: false,
    price: 28,
    originalPrice: 35,
    deliveryTime: "Same day",
    rating: 4.4,
    reviewCount: 31,
    images: gallery(
      imageLibrary.chillies,
      imageLibrary.leafy,
      imageLibrary.heroHarvest,
    ),
    color: "from-green-100 to-lime-50",
    harvestDate: "2026-04-29",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-15",
    name: "Cold Pressed Groundnut Oil",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "Filtered groundnut oil with a strong roasted aroma for home cooking and snack shops.",
    tags: ["Oil", "Cold pressed", "Pantry"],
    unit: "1 litre",
    stock: 44,
    organic: true,
    price: 340,
    originalPrice: 390,
    deliveryTime: "2-4 days",
    rating: 4.7,
    reviewCount: 24,
    images: gallery(
      imageLibrary.oil,
      imageLibrary.spices,
      imageLibrary.grains,
    ),
    color: "from-amber-100 to-yellow-50",
    harvestDate: "2026-04-16",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-16",
    name: "Dhaniya Beej Pack",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "seeds",
    state: "Punjab",
    description:
      "Dhaniya seeds packed for kitchen gardens, terrace pots and small trial sowing.",
    tags: ["Beej", "Home garden", "Starter pack"],
    unit: "200 g",
    stock: 86,
    organic: false,
    price: 120,
    originalPrice: 155,
    deliveryTime: "2-5 days",
    rating: 4.2,
    reviewCount: 17,
    images: gallery(
      imageLibrary.seeds,
      imageLibrary.nursery,
      imageLibrary.leafy,
    ),
    color: "from-rose-100 to-orange-50",
    harvestDate: "2026-04-11",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-17",
    name: "NPK 19:19:19 Water Soluble Fertiliser",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "fertilisers",
    state: "Punjab",
    description:
      "Balanced NPK fertiliser for vegetables, fruits and nursery crops, suitable for drip and foliar use.",
    tags: ["Fertiliser", "Water soluble", "High demand"],
    unit: "5 kg bag",
    stock: 64,
    organic: false,
    price: 1290,
    originalPrice: 1440,
    deliveryTime: "2-4 days",
    rating: 4.6,
    reviewCount: 22,
    images: gallery(
      imageLibrary.fertilizer,
      imageLibrary.heroGreenhouse,
      imageLibrary.nursery,
    ),
    color: "from-lime-100 to-white",
    harvestDate: "2026-04-19",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-18",
    name: "Neem Shield Bio Pesticide",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "crop-care",
    state: "Maharashtra",
    description:
      "Neem-based crop protection spray for sucking pests in vegetables, fruits and flower crops.",
    tags: ["Pesticide", "Neem based", "Crop protection"],
    unit: "1 litre",
    stock: 88,
    organic: true,
    price: 540,
    originalPrice: 620,
    deliveryTime: "2-3 days",
    rating: 4.5,
    reviewCount: 19,
    images: gallery(
      imageLibrary.pesticide,
      imageLibrary.heroHarvest,
      imageLibrary.nursery,
    ),
    color: "from-green-100 to-emerald-50",
    harvestDate: "2026-04-24",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-19",
    name: "Vermicompost Premium Grade",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "fertilisers",
    state: "Karnataka",
    description:
      "Nutrient-rich vermicompost for kitchen gardens, polyhouse cultivation and organic field applications.",
    tags: ["Organic input", "Compost", "Soil health"],
    unit: "25 kg bag",
    stock: 40,
    organic: true,
    price: 430,
    originalPrice: 520,
    deliveryTime: "3-5 days",
    rating: 4.7,
    reviewCount: 16,
    images: gallery(
      imageLibrary.compost,
      imageLibrary.heroGreenhouse,
      imageLibrary.nursery,
    ),
    color: "from-lime-100 to-green-50",
    harvestDate: "2026-04-18",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-20",
    name: "Micronutrient Mix for Chilli and Tomato",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "crop-care",
    state: "Punjab",
    description:
      "Foliar micronutrient mix to support flowering, fruit set and leaf strength in solanaceous crops.",
    tags: ["Micronutrients", "Vegetable crops", "Foliar spray"],
    unit: "1 kg pack",
    stock: 52,
    organic: false,
    price: 620,
    originalPrice: 710,
    deliveryTime: "2-4 days",
    rating: 4.4,
    reviewCount: 11,
    images: gallery(
      imageLibrary.fertilizer,
      imageLibrary.tomato,
      imageLibrary.chillies,
    ),
    color: "from-emerald-100 to-white",
    harvestDate: "2026-04-21",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-21",
    name: "Cocopeat Grow Bags",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "seeds",
    state: "Maharashtra",
    description:
      "Compressed cocopeat grow bags suitable for nursery trays, terrace gardens and protected cultivation.",
    tags: ["Nursery", "Grow media", "Kitchen garden"],
    unit: "5 block set",
    stock: 70,
    organic: true,
    price: 360,
    originalPrice: 430,
    deliveryTime: "2-4 days",
    rating: 4.5,
    reviewCount: 13,
    images: gallery(
      imageLibrary.nursery,
      imageLibrary.compost,
      imageLibrary.heroGreenhouse,
    ),
    color: "from-rose-100 to-white",
    harvestDate: "2026-04-22",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-22",
    name: "Bio Potash Granules",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "fertilisers",
    state: "Karnataka",
    description:
      "Potash-rich granules designed to support root strength, fruit quality and overall crop vigour.",
    tags: ["Potash", "Fruit quality", "Field crops"],
    unit: "10 kg bag",
    stock: 48,
    organic: false,
    price: 980,
    originalPrice: 1090,
    deliveryTime: "2-4 days",
    rating: 4.6,
    reviewCount: 14,
    images: gallery(
      imageLibrary.fertilizer,
      imageLibrary.heroHarvest,
      imageLibrary.compost,
    ),
    color: "from-lime-100 to-white",
    harvestDate: "2026-04-17",
    featured: true,
    trending: false,
  }),
];

export const reviewsByProduct: Record<string, Review[]> = {
  "prod-1": [
    {
      id: "review-1",
      userName: "Neha S.",
      rating: 5,
      comment: "Perfect ripeness and premium packing. Worth the seasonal premium.",
      createdAt: "2026-04-22",
    },
    {
      id: "review-2",
      userName: "FreshMart Retail",
      rating: 4,
      comment: "Uniform sizing and good shelf life for our weekend sale.",
      createdAt: "2026-04-21",
    },
  ],
  "prod-2": [
    {
      id: "review-3",
      userName: "Amit V.",
      rating: 5,
      comment: "Palak was fresh, green and clean. Worked really well for paratha and dal.",
      createdAt: "2026-04-27",
    },
  ],
};

export const users: DemoUser[] = [
  {
    id: "user-1",
    name: "Priya Sharma",
    email: "buyer@greencart.in",
    mobile: "9876543210",
    role: "buyer",
    password: "password123",
    avatar: "PS",
    wishlist: ["prod-1", "prod-7"],
    addresses: [
      {
        id: "addr-1",
        label: "Home",
        recipient: "Priya Sharma",
        line1: "42, Green Residency, Sector 62",
        city: "Noida",
        state: "Uttar Pradesh",
        pincode: "201301",
        phone: "9876543210",
        primary: true,
      },
    ],
  },
  {
    id: "user-2",
    name: "Rakesh Kumar",
    email: "farmer@greencart.in",
    mobile: "9988776655",
    role: "farmer",
    password: "password123",
    avatar: "RK",
    farmerId: "farmer-1",
    wishlist: ["prod-3"],
    addresses: [
      {
        id: "addr-2",
        label: "Farm Office",
        recipient: "Rakesh Kumar",
        line1: "Village Jodhan, Ludhiana",
        city: "Ludhiana",
        state: "Punjab",
        pincode: "141001",
        phone: "9988776655",
        primary: true,
      },
    ],
  },
  {
    id: "user-3",
    name: "Admin GreenCart",
    email: "admin@greencart.in",
    mobile: "9000000000",
    role: "admin",
    password: "password123",
    avatar: "AG",
    wishlist: [],
    addresses: [],
  },
  {
    id: "user-4",
    name: "Anita Patil",
    email: "anita@greencart.in",
    mobile: "9898989898",
    role: "farmer",
    password: "password123",
    avatar: "AP",
    farmerId: "farmer-2",
    wishlist: [],
    addresses: [
      {
        id: "addr-4",
        label: "Farm Office",
        recipient: "Anita Patil",
        line1: "Pimpalgaon Baswant, Nashik",
        city: "Nashik",
        state: "Maharashtra",
        pincode: "422209",
        phone: "9898989898",
        primary: true,
      },
    ],
  },
  {
    id: "user-5",
    name: "Mahesh Gowda",
    email: "mahesh@greencart.in",
    mobile: "9797979797",
    role: "farmer",
    password: "password123",
    avatar: "MG",
    farmerId: "farmer-3",
    wishlist: [],
    addresses: [
      {
        id: "addr-5",
        label: "Farm Office",
        recipient: "Mahesh Gowda",
        line1: "Hunsur Road, Mysuru",
        city: "Mysuru",
        state: "Karnataka",
        pincode: "570017",
        phone: "9797979797",
        primary: true,
      },
    ],
  },
];

export const orders: Order[] = [
  {
    id: "ORD-240401",
    userId: "user-1",
    items: [
      { productId: "prod-1", quantity: 1, price: 899 },
      { productId: "prod-2", quantity: 2, price: 85 },
    ],
    subtotal: 1069,
    deliveryCharge: 40,
    discount: 100,
    total: 1009,
    paymentMode: "UPI",
    status: "In Transit",
    placedAt: "2026-04-25T10:30:00.000Z",
    estimatedDelivery: "2026-04-30T18:00:00.000Z",
    address: users[0].addresses[0],
  },
  {
    id: "ORD-240389",
    userId: "user-1",
    items: [{ productId: "prod-4", quantity: 1, price: 399 }],
    subtotal: 399,
    deliveryCharge: 0,
    discount: 0,
    total: 399,
    paymentMode: "COD",
    status: "Delivered",
    placedAt: "2026-04-14T13:20:00.000Z",
    estimatedDelivery: "2026-04-17T18:00:00.000Z",
    address: users[0].addresses[0],
  },
];

export const mandiRatesFallback: MandiRate[] = [
  {
    commodity: "Onion",
    market: "Lasalgaon",
    state: "Maharashtra",
    modalPrice: 1800,
    minPrice: 1650,
    maxPrice: 1960,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Tomato",
    market: "Kolar",
    state: "Karnataka",
    modalPrice: 1250,
    minPrice: 980,
    maxPrice: 1380,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Potato",
    market: "Agra",
    state: "Uttar Pradesh",
    modalPrice: 1420,
    minPrice: 1300,
    maxPrice: 1580,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Mango",
    market: "Vashi",
    state: "Maharashtra",
    modalPrice: 5200,
    minPrice: 4700,
    maxPrice: 6100,
    arrivalDate: "2026-04-28",
  },
];

export const weatherInsightsFallback: WeatherInsight[] = [
  {
    title: "Rainfall watch",
    value: "18 mm",
    note: "Moderate showers expected across western Maharashtra over the next 48 hours.",
  },
  {
    title: "Soil moisture",
    value: "62%",
    note: "Good field moisture in Punjab vegetable belts; irrigation can be deferred for leafy crops.",
  },
  {
    title: "Crop alert",
    value: "Mango thrips",
    note: "Use sticky traps and field scouting in high humidity clusters.",
  },
];

export const farmerSalesMetrics: DashboardMetric[] = [
  {
    label: "This month sales",
    value: "Rs1.84L",
    change: "+14.2%",
    tone: "positive",
  },
  {
    label: "Pending dispatches",
    value: "26",
    change: "6 due today",
    tone: "warning",
  },
  {
    label: "Average order value",
    value: "Rs1,420",
    change: "+6.8%",
    tone: "positive",
  },
  {
    label: "Catalogue health",
    value: "92%",
    change: "3 items low stock",
    tone: "neutral",
  },
];

export const adminMetrics: DashboardMetric[] = [
  {
    label: "GMV this month",
    value: "Rs18.6L",
    change: "+18%",
    tone: "positive",
  },
  {
    label: "Verified farmers",
    value: "128",
    change: "12 pending review",
    tone: "neutral",
  },
  {
    label: "Orders today",
    value: "482",
    change: "+9.1%",
    tone: "positive",
  },
  {
    label: "Support SLA",
    value: "97%",
    change: "Healthy",
    tone: "positive",
  },
];
